### ISSUE TITLE
can u try to explain: var_search_length?

### ISSUE THREAD

**Issue by flippz** [dala318/nordpool_planner#10]
I cant get my head around this integration. Could you please explain var_search_length again in other words than in the readme?
Maybe Swedish would help as im Norwegian.

**Comment by dala318** [comment]
It will be updated in pull request #9 and renamed to "var_duration_entity_id"
So the idea is that instead of setting a fixed length of cheap hours in the configuration.yaml you point it to an entity (typically an "input_number" as example below and then the value of that sensor get used) 

The input number:
```yaml
input_number:
  np_duration:
    name: Slider
    initial: 2
    min: 0
    max: 24
    step: 1
```

And then your nordpool_planner:
```yaml
binary_sensor:
  - platform: nordpool_planner
    entity_id: moving_1
    nordpool_entity: sensor.nordpool_kwh_se3_sek_3_10_025
    var_search_length: input_number.np_duration
```
