### ISSUE TITLE
outcome not in line with expectations (1 hour off)

### ISSUE THREAD

**Issue by ronaldt80** [dala318/nordpool_planner#12]
Hi, I have been playing around with the tool for a few days and found that the outcome is not optimal, eg. in this case one hour off; what's the best way to debug?

I want the start time for the cheapest 4 hour period in a max 24 hour time horizon (rolling) - based on the nordpool sensor my binary planning sensor generates 19:00 with an average cost of 41cents [calculation is correct adding up 19 - 23pm / 4]; however, starting one hour later (20:00) would generate a lower average of 35cents. Any thoughts what I am doing wrong?

YAML code:
```
 binary_sensor:   
 -  platform: nordpool_planner
    nordpool_entity: sensor.nordpool_kwh_nl_eur_3_10_009
    entity_id: optimal_start_time_dishwasher
    duration: 4
    moving:
      search_length: 24
```

Used nordpool data:
```
  - start: '2022-11-29T19:00:00+01:00'
    end: '2022-11-29T20:00:00+01:00'
    value: 0.506
  - start: '2022-11-29T20:00:00+01:00'
    end: '2022-11-29T21:00:00+01:00'
    value: 0.436
  - start: '2022-11-29T21:00:00+01:00'
    end: '2022-11-29T22:00:00+01:00'
    value: 0.365
  - start: '2022-11-29T22:00:00+01:00'
    end: '2022-11-29T23:00:00+01:00'
    value: 0.324
  - start: '2022-11-29T23:00:00+01:00'
    end: '2022-11-30T00:00:00+01:00'
    value: 0.278
```

**Comment by dala318** [comment]
It does not seem you are doing anything wrong, but the plug-in is doing something wrong.

**Comment by dala318** [comment]
The only way I know of to debug is to run it in the HASS development environment. Once you find the guide it's quite easy to follow and setup, and integrates well with VS Code.

**Comment by rolis1122** [comment]
Hi. Found your custom HACS integration and found it very cool. Thanks for your job! :)
As mentioned before - seems that best period found by sensor is off by 1 hour as commmented in 1st post.
I'm not good at programming at all, but hope You will find time to look at code any time soon :)

**Comment by dala318** [comment]
After fixing #13 in #14 I also found a spot in prices to try to reproduce this issue but seem to function as expected, could be that #14 fixed this one as well. Please update to v.0.2.3 and see if you agree.

```
binary_sensor:
  - platform: nordpool_planner
    entity_id: moving_1
    nordpool_entity: sensor.nordpool_kwh_se3_sek_3_10_025
    duration: 3
    moving:
      search_length: 6
```

Ignore noise in binary sensor history graph before 13:30 as that was during my testing of other prameters
![image](https://user-images.githubusercontent.com/20300390/224325090-ae800547-a9a5-42d9-8cf1-2f00ee00d704.png)

**Comment by Danny-DFx** [comment]
Hi.
I play around with the planner the last days, because I want to charge my Luna Battery automaticly, when the prices are at the lowest at that day.
I used the planner, and I had the same issue like @ronaldt80 reported it. But at my setup, with a 3 hour off, today or better tomorrow night is the lowest price at 3, but the planner activate at 0. 

![image](https://github.com/dala318/nordpool_planner/assets/149078331/254ee213-3ab8-46bb-bbfe-ca84a8a186e8)

Nordpool Data:

```
- start: '2023-12-28T22:00:00+01:00'
end: '2023-12-28T23:00:00+01:00'
value: 1.772
- start: '2023-12-28T23:00:00+01:00'
end: '2023-12-29T00:00:00+01:00'
value: 0.1
Raw tomorrow
- start: '2023-12-29T00:00:00+01:00'
end: '2023-12-29T01:00:00+01:00'
value: 0
- start: '2023-12-29T01:00:00+01:00'
end: '2023-12-29T02:00:00+01:00'
value: -0.008
- start: '2023-12-29T02:00:00+01:00'
end: '2023-12-29T03:00:00+01:00'
value: -0.028
- start: '2023-12-29T03:00:00+01:00'
end: '2023-12-29T04:00:00+01:00'
value: -0.093
- start: '2023-12-29T04:00:00+01:00'
end: '2023-12-29T05:00:00+01:00'
value: -0.095
- start: '2023-12-29T05:00:00+01:00'
end: '2023-12-29T06:00:00+01:00'
value: -0.026
```

My binary sensor:

```
binary_sensor:
  - platform: nordpool_planner
    nordpool_entity: sensor.nordpool_kwh_de_lu_eur_4_10_0
    entity_id: Planner
    duration: 2
    
    moving:
      search_length: 24
```

My expectation is, the the binary sensor activate at 3am and ends at 5am.
What I'm doing wrong? (I'm relative new to HA and all these things, but I can't solve this at the moment, cause I didn't know what to look after... ;-) 
What do you need for files, maybe this is a bug? I would like to send you debug files, but I struggle to get them at the moment... Sorry. 

Maybe you have an idea how to solve it?
Thanks in advance.

Kind regards.
Daniel

**Comment by Danny-DFx** [comment]
Good morning.
An addition to the problem.
The binary sensor activated at 1am last night when the price was below 0 cent, until 8am this morning when the price was above 0 cent. 
This suggests that the problem could be with prices below 0 cent.
Please find attached my Nordpool prices and the status of the sensor last night.

I would be pleased to receive a reply.
Thank you very much.

Best regards
Daniel

```
today: 0, -0.008, -0.028, -0.093, -0.095, -0.026, -0.007, -0.001, 0.444, 0.109, 0.005, -0.001, 0.06, 0.099, 0.223, 0.999, 1.002, 2.512, 2.659, 1.717, 1.01, 0.504, 2.29, 1.889
tomorrow: 
tomorrow_valid: false
raw_today: 
- start: '2023-12-29T00:00:00+01:00'
  end: '2023-12-29T01:00:00+01:00'
  value: 0
- start: '2023-12-29T01:00:00+01:00'
  end: '2023-12-29T02:00:00+01:00'
  value: -0.008
- start: '2023-12-29T02:00:00+01:00'
  end: '2023-12-29T03:00:00+01:00'
  value: -0.028
- start: '2023-12-29T03:00:00+01:00'
  end: '2023-12-29T04:00:00+01:00'
  value: -0.093
- start: '2023-12-29T04:00:00+01:00'
  end: '2023-12-29T05:00:00+01:00'
  value: -0.095
- start: '2023-12-29T05:00:00+01:00'
  end: '2023-12-29T06:00:00+01:00'
  value: -0.026
- start: '2023-12-29T06:00:00+01:00'
  end: '2023-12-29T07:00:00+01:00'
  value: -0.007
- start: '2023-12-29T07:00:00+01:00'
  end: '2023-12-29T08:00:00+01:00'
  value: -0.001
- start: '2023-12-29T08:00:00+01:00'
  end: '2023-12-29T09:00:00+01:00'
  value: 0.444
- start: '2023-12-29T09:00:00+01:00'
  end: '2023-12-29T10:00:00+01:00'
  value: 0.109
- start: '2023-12-29T10:00:00+01:00'
  end: '2023-12-29T11:00:00+01:00'
  value: 0.005
- start: '2023-12-29T11:00:00+01:00'
  end: '2023-12-29T12:00:00+01:00'
  value: -0.001
- start: '2023-12-29T12:00:00+01:00'
  end: '2023-12-29T13:00:00+01:00'
  value: 0.06
- start: '2023-12-29T13:00:00+01:00'
  end: '2023-12-29T14:00:00+01:00'
  value: 0.099
- start: '2023-12-29T14:00:00+01:00'
  end: '2023-12-29T15:00:00+01:00'
  value: 0.223
- start: '2023-12-29T15:00:00+01:00'
  end: '2023-12-29T16:00:00+01:00'
  value: 0.999
- start: '2023-12-29T16:00:00+01:00'
  end: '2023-12-29T17:00:00+01:00'
  value: 1.002
- start: '2023-12-29T17:00:00+01:00'
  end: '2023-12-29T18:00:00+01:00'
  value: 2.512
- start: '2023-12-29T18:00:00+01:00'
  end: '2023-12-29T19:00:00+01:00'
  value: 2.659
- start: '2023-12-29T19:00:00+01:00'
  end: '2023-12-29T20:00:00+01:00'
  value: 1.717
- start: '2023-12-29T20:00:00+01:00'
  end: '2023-12-29T21:00:00+01:00'
  value: 1.01
- start: '2023-12-29T21:00:00+01:00'
  end: '2023-12-29T22:00:00+01:00'
  value: 0.504
- start: '2023-12-29T22:00:00+01:00'
  end: '2023-12-29T23:00:00+01:00'
  value: 2.29
- start: '2023-12-29T23:00:00+01:00'
  end: '2023-12-30T00:00:00+01:00'
  value: 1.889
```


```
starts_at: 2023-12-29 10:00
cost_at: 0.002
now_cost_rate: 222
icon: mdi:flash
friendly_name: nordpool_planner_Planner
```

![image](https://github.com/dala318/nordpool_planner/assets/149078331/75c15535-e7d6-4862-983a-5538cda04388)
