### ISSUE TITLE
Duration offset / too long and lowest price not match

### ISSUE THREAD

**Issue by Danny-DFx** [dala318/nordpool_planner#24]
Hi.
I play around with the planner the last days, because I want to charge my Luna Battery automatically, when the prices are at the lowest at that day.
I used the planner, and I had the same issue like @ronaldt80 reported it. But at my setup, with a 3 hour off, today or better tomorrow night is the lowest price at 3, but the planner activate at 0. 

![image](https://github.com/dala318/nordpool_planner/assets/149078331/254ee213-3ab8-46bb-bbfe-ca84a8a186e8)

Nordpool Data:

```
- start: '2023-12-28T22:00:00+01:00'
end: '2023-12-28T23:00:00+01:00'
value: 1.772
- start: '2023-12-28T23:00:00+01:00'
end: '2023-12-29T00:00:00+01:00'
value: 0.1
Raw tomorrow
- start: '2023-12-29T00:00:00+01:00'
end: '2023-12-29T01:00:00+01:00'
value: 0
- start: '2023-12-29T01:00:00+01:00'
end: '2023-12-29T02:00:00+01:00'
value: -0.008
- start: '2023-12-29T02:00:00+01:00'
end: '2023-12-29T03:00:00+01:00'
value: -0.028
- start: '2023-12-29T03:00:00+01:00'
end: '2023-12-29T04:00:00+01:00'
value: -0.093
- start: '2023-12-29T04:00:00+01:00'
end: '2023-12-29T05:00:00+01:00'
value: -0.095
- start: '2023-12-29T05:00:00+01:00'
end: '2023-12-29T06:00:00+01:00'
value: -0.026
```

My binary sensor:

```
binary_sensor:
  - platform: nordpool_planner
    nordpool_entity: sensor.nordpool_kwh_de_lu_eur_4_10_0
    entity_id: Planner
    duration: 2
    
    moving:
      search_length: 24
```

My expectation is, the binary sensor activate at 3am and ends at 5am.
What I'm doing wrong? (I'm relative new to HA and all these things, but I can't solve this at the moment, cause I didn't know what to look after... ;-) 
What do you need for files, maybe this is a bug? I would like to send you debug files, but I struggle to get them at the moment... Sorry. 

Maybe you have an idea how to solve it?
Thanks in advance.

++++

Good morning.
An addition to the problem.
The binary sensor activated at 1am last night when the price was below 0 cent, until 8am this morning when the price was above 0 cent. 
This suggests that the problem could be with prices below 0 cent.
Please find attached my Nordpool prices and the status of the sensor last night.

I would be pleased to receive a reply.
Thank you very much.

Best regards
Daniel

```
today: 0, -0.008, -0.028, -0.093, -0.095, -0.026, -0.007, -0.001, 0.444, 0.109, 0.005, -0.001, 0.06, 0.099, 0.223, 0.999, 1.002, 2.512, 2.659, 1.717, 1.01, 0.504, 2.29, 1.889
tomorrow: 
tomorrow_valid: false
raw_today: 
- start: '2023-12-29T00:00:00+01:00'
  end: '2023-12-29T01:00:00+01:00'
  value: 0
- start: '2023-12-29T01:00:00+01:00'
  end: '2023-12-29T02:00:00+01:00'
  value: -0.008
- start: '2023-12-29T02:00:00+01:00'
  end: '2023-12-29T03:00:00+01:00'
  value: -0.028
- start: '2023-12-29T03:00:00+01:00'
  end: '2023-12-29T04:00:00+01:00'
  value: -0.093
- start: '2023-12-29T04:00:00+01:00'
  end: '2023-12-29T05:00:00+01:00'
  value: -0.095
- start: '2023-12-29T05:00:00+01:00'
  end: '2023-12-29T06:00:00+01:00'
  value: -0.026
- start: '2023-12-29T06:00:00+01:00'
  end: '2023-12-29T07:00:00+01:00'
  value: -0.007
- start: '2023-12-29T07:00:00+01:00'
  end: '2023-12-29T08:00:00+01:00'
  value: -0.001
- start: '2023-12-29T08:00:00+01:00'
  end: '2023-12-29T09:00:00+01:00'
  value: 0.444
- start: '2023-12-29T09:00:00+01:00'
  end: '2023-12-29T10:00:00+01:00'
  value: 0.109
- start: '2023-12-29T10:00:00+01:00'
  end: '2023-12-29T11:00:00+01:00'
  value: 0.005
- start: '2023-12-29T11:00:00+01:00'
  end: '2023-12-29T12:00:00+01:00'
  value: -0.001
- start: '2023-12-29T12:00:00+01:00'
  end: '2023-12-29T13:00:00+01:00'
  value: 0.06
- start: '2023-12-29T13:00:00+01:00'
  end: '2023-12-29T14:00:00+01:00'
  value: 0.099
- start: '2023-12-29T14:00:00+01:00'
  end: '2023-12-29T15:00:00+01:00'
  value: 0.223
- start: '2023-12-29T15:00:00+01:00'
  end: '2023-12-29T16:00:00+01:00'
  value: 0.999
- start: '2023-12-29T16:00:00+01:00'
  end: '2023-12-29T17:00:00+01:00'
  value: 1.002
- start: '2023-12-29T17:00:00+01:00'
  end: '2023-12-29T18:00:00+01:00'
  value: 2.512
- start: '2023-12-29T18:00:00+01:00'
  end: '2023-12-29T19:00:00+01:00'
  value: 2.659
- start: '2023-12-29T19:00:00+01:00'
  end: '2023-12-29T20:00:00+01:00'
  value: 1.717
- start: '2023-12-29T20:00:00+01:00'
  end: '2023-12-29T21:00:00+01:00'
  value: 1.01
- start: '2023-12-29T21:00:00+01:00'
  end: '2023-12-29T22:00:00+01:00'
  value: 0.504
- start: '2023-12-29T22:00:00+01:00'
  end: '2023-12-29T23:00:00+01:00'
  value: 2.29
- start: '2023-12-29T23:00:00+01:00'
  end: '2023-12-30T00:00:00+01:00'
  value: 1.889
```

```
starts_at: 2023-12-29 10:00
cost_at: 0.002
now_cost_rate: 222
icon: mdi:flash
friendly_name: nordpool_planner_Planner
```

![image](https://github.com/dala318/nordpool_planner/assets/149078331/75c15535-e7d6-4862-983a-5538cda04388)

+++

Good morning.
An addition to the problem.
The binary sensor activated at 1am last night when the price was below 0 cent, until 8am this morning when the price was above 0 cent. 
This suggests that the problem could be with prices below 0 cent.
Please find attached my Nordpool prices and the status of the sensor last night.

I would be pleased to receive a reply.
Thank you very much.

Best regards
Daniel

```
today: 0, -0.008, -0.028, -0.093, -0.095, -0.026, -0.007, -0.001, 0.444, 0.109, 0.005, -0.001, 0.06, 0.099, 0.223, 0.999, 1.002, 2.512, 2.659, 1.717, 1.01, 0.504, 2.29, 1.889
tomorrow: 
tomorrow_valid: false
raw_today: 
- start: '2023-12-29T00:00:00+01:00'
  end: '2023-12-29T01:00:00+01:00'
  value: 0
- start: '2023-12-29T01:00:00+01:00'
  end: '2023-12-29T02:00:00+01:00'
  value: -0.008
- start: '2023-12-29T02:00:00+01:00'
  end: '2023-12-29T03:00:00+01:00'
  value: -0.028
- start: '2023-12-29T03:00:00+01:00'
  end: '2023-12-29T04:00:00+01:00'
  value: -0.093
- start: '2023-12-29T04:00:00+01:00'
  end: '2023-12-29T05:00:00+01:00'
  value: -0.095
- start: '2023-12-29T05:00:00+01:00'
  end: '2023-12-29T06:00:00+01:00'
  value: -0.026
- start: '2023-12-29T06:00:00+01:00'
  end: '2023-12-29T07:00:00+01:00'
  value: -0.007
- start: '2023-12-29T07:00:00+01:00'
  end: '2023-12-29T08:00:00+01:00'
  value: -0.001
- start: '2023-12-29T08:00:00+01:00'
  end: '2023-12-29T09:00:00+01:00'
  value: 0.444
- start: '2023-12-29T09:00:00+01:00'
  end: '2023-12-29T10:00:00+01:00'
  value: 0.109
- start: '2023-12-29T10:00:00+01:00'
  end: '2023-12-29T11:00:00+01:00'
  value: 0.005
- start: '2023-12-29T11:00:00+01:00'
  end: '2023-12-29T12:00:00+01:00'
  value: -0.001
- start: '2023-12-29T12:00:00+01:00'
  end: '2023-12-29T13:00:00+01:00'
  value: 0.06
- start: '2023-12-29T13:00:00+01:00'
  end: '2023-12-29T14:00:00+01:00'
  value: 0.099
- start: '2023-12-29T14:00:00+01:00'
  end: '2023-12-29T15:00:00+01:00'
  value: 0.223
- start: '2023-12-29T15:00:00+01:00'
  end: '2023-12-29T16:00:00+01:00'
  value: 0.999
- start: '2023-12-29T16:00:00+01:00'
  end: '2023-12-29T17:00:00+01:00'
  value: 1.002
- start: '2023-12-29T17:00:00+01:00'
  end: '2023-12-29T18:00:00+01:00'
  value: 2.512
- start: '2023-12-29T18:00:00+01:00'
  end: '2023-12-29T19:00:00+01:00'
  value: 2.659
- start: '2023-12-29T19:00:00+01:00'
  end: '2023-12-29T20:00:00+01:00'
  value: 1.717
- start: '2023-12-29T20:00:00+01:00'
  end: '2023-12-29T21:00:00+01:00'
  value: 1.01
- start: '2023-12-29T21:00:00+01:00'
  end: '2023-12-29T22:00:00+01:00'
  value: 0.504
- start: '2023-12-29T22:00:00+01:00'
  end: '2023-12-29T23:00:00+01:00'
  value: 2.29
- start: '2023-12-29T23:00:00+01:00'
  end: '2023-12-30T00:00:00+01:00'
  value: 1.889
```

```
starts_at: 2023-12-29 10:00
cost_at: 0.002
now_cost_rate: 222
icon: mdi:flash
friendly_name: nordpool_planner_Planner
```

![image](https://github.com/dala318/nordpool_planner/assets/149078331/75c15535-e7d6-4862-983a-5538cda04388)

+++

Good morning.
So, today is another day while the planner switch to on and it is not the cheapest time of the day, later it was "cheaper", but another issue, the price is gone up to 4ct. and the planner did not switch off. Take a look in the attachment.

Do you have any ideas to solve this?

Thanks in advance,
Kind regards.
Daniel

![image](https://github.com/dala318/nordpool_planner/assets/149078331/1dbc4c80-4730-4c48-9ccf-c433e3b23933)

```
Average
4,52
Off peak 1
0,44
Off peak 2
6,59
Peak
6,55
Min
-0,14
Max
8,3
Mean
5,76
Unit
kWh
Currency
EUR
Country
Germany and Luxembourg
Region
DE-LU
Low price
true
Price percent to average
0,9
Today
-0,01, -0,12, -0,13, -0,13, -0,13, -0,14, 0,11, 4,06, 5,96, 6,06, 5,7, 5,49, 5,39, 5,44, 6,09, 6,72, 7,36, 8,23, 8,3, 7,9, 7,32, 6,74, 6,5, 5,81
Tomorrow
Tomorrow valid
false
Raw today
- start: '2024-01-03T00:00:00+01:00'
end: '2024-01-03T01:00:00+01:00'
value: -0.008
- start: '2024-01-03T01:00:00+01:00'
end: '2024-01-03T02:00:00+01:00'
value: -0.123
- start: '2024-01-03T02:00:00+01:00'
end: '2024-01-03T03:00:00+01:00'
value: -0.13
- start: '2024-01-03T03:00:00+01:00'
end: '2024-01-03T04:00:00+01:00'
value: -0.131
- start: '2024-01-03T04:00:00+01:00'
end: '2024-01-03T05:00:00+01:00'
value: -0.131
- start: '2024-01-03T05:00:00+01:00'
end: '2024-01-03T06:00:00+01:00'
value: -0.138
- start: '2024-01-03T06:00:00+01:00'
end: '2024-01-03T07:00:00+01:00'
value: 0.109
- start: '2024-01-03T07:00:00+01:00'
end: '2024-01-03T08:00:00+01:00'
value: 4.059
- start: '2024-01-03T08:00:00+01:00'
end: '2024-01-03T09:00:00+01:00'
value: 5.961
- start: '2024-01-03T09:00:00+01:00'
end: '2024-01-03T10:00:00+01:00'
value: 6.061
- start: '2024-01-03T10:00:00+01:00'
end: '2024-01-03T11:00:00+01:00'
value: 5.7
- start: '2024-01-03T11:00:00+01:00'
end: '2024-01-03T12:00:00+01:00'
value: 5.489
- start: '2024-01-03T12:00:00+01:00'
end: '2024-01-03T13:00:00+01:00'
value: 5.389
- start: '2024-01-03T13:00:00+01:00'
end: '2024-01-03T14:00:00+01:00'
value: 5.442
- start: '2024-01-03T14:00:00+01:00'
end: '2024-01-03T15:00:00+01:00'
value: 6.086
- start: '2024-01-03T15:00:00+01:00'
end: '2024-01-03T16:00:00+01:00'
value: 6.718
- start: '2024-01-03T16:00:00+01:00'
end: '2024-01-03T17:00:00+01:00'
value: 7.359
- start: '2024-01-03T17:00:00+01:00'
end: '2024-01-03T18:00:00+01:00'
value: 8.228
- start: '2024-01-03T18:00:00+01:00'
end: '2024-01-03T19:00:00+01:00'
value: 8.297
- start: '2024-01-03T19:00:00+01:00'
end: '2024-01-03T20:00:00+01:00'
value: 7.903
- start: '2024-01-03T20:00:00+01:00'
end: '2024-01-03T21:00:00+01:00'
value: 7.323
- start: '2024-01-03T21:00:00+01:00'
end: '2024-01-03T22:00:00+01:00'
value: 6.741
- start: '2024-01-03T22:00:00+01:00'
end: '2024-01-03T23:00:00+01:00'
value: 6.5
- start: '2024-01-03T23:00:00+01:00'
end: '2024-01-04T00:00:00+01:00'
value: 5.812
Raw tomorrow
Current price
4,06
Additional costs current hour
0
Price in cents
true
```

![image](https://github.com/dala318/nordpool_planner/assets/149078331/4273a03d-6a9d-441b-9014-18570946c20e)

_Originally posted by @Danny-DFx in https://github.com/dala318/nordpool_planner/issues/12#issuecomment-1871305398_

**Comment by Danny-DFx** [comment]
And in addition, today the same behavior, the Sensor  switches on at 3 and is still active, but we are far away  from the lowest prices. Maybe I understand something wrong, but after the duration = 2, my understanding is, that the binary sensor switches off.

```
state_class: total
average: 8.541
off_peak_1: 5.2955000000000005
off_peak_2: 9.68225
peak: 10.32425
min: 2.548
max: 14.465
mean: 9.075
unit: kWh
currency: EUR
country: Germany and Luxembourg
region: DE-LU
low_price: true
price_percent_to_average: 0.995433789954338
today: 5.73, 5.046, 4, 2.548, 3.5, 5.773, 7.265, 8.502, 9.147, 9.42, 9.161, 9.003, 8.63, 8.596, 9.211, 9.862, 10.573, 13.323, 14.465, 12.5, 10.359, 10.001, 9.486, 8.883
tomorrow: 
tomorrow_valid: false
raw_today: 
- start: '2024-01-04T00:00:00+01:00'
  end: '2024-01-04T01:00:00+01:00'
  value: 5.73
- start: '2024-01-04T01:00:00+01:00'
  end: '2024-01-04T02:00:00+01:00'
  value: 5.046
- start: '2024-01-04T02:00:00+01:00'
  end: '2024-01-04T03:00:00+01:00'
  value: 4
- start: '2024-01-04T03:00:00+01:00'
  end: '2024-01-04T04:00:00+01:00'
  value: 2.548
- start: '2024-01-04T04:00:00+01:00'
  end: '2024-01-04T05:00:00+01:00'
  value: 3.5
- start: '2024-01-04T05:00:00+01:00'
  end: '2024-01-04T06:00:00+01:00'
  value: 5.773
- start: '2024-01-04T06:00:00+01:00'
  end: '2024-01-04T07:00:00+01:00'
  value: 7.265
- start: '2024-01-04T07:00:00+01:00'
  end: '2024-01-04T08:00:00+01:00'
  value: 8.502
- start: '2024-01-04T08:00:00+01:00'
  end: '2024-01-04T09:00:00+01:00'
  value: 9.147
- start: '2024-01-04T09:00:00+01:00'
  end: '2024-01-04T10:00:00+01:00'
  value: 9.42
- start: '2024-01-04T10:00:00+01:00'
  end: '2024-01-04T11:00:00+01:00'
  value: 9.161
- start: '2024-01-04T11:00:00+01:00'
  end: '2024-01-04T12:00:00+01:00'
  value: 9.003
- start: '2024-01-04T12:00:00+01:00'
  end: '2024-01-04T13:00:00+01:00'
  value: 8.63
- start: '2024-01-04T13:00:00+01:00'
  end: '2024-01-04T14:00:00+01:00'
  value: 8.596
- start: '2024-01-04T14:00:00+01:00'
  end: '2024-01-04T15:00:00+01:00'
  value: 9.211
- start: '2024-01-04T15:00:00+01:00'
  end: '2024-01-04T16:00:00+01:00'
  value: 9.862
- start: '2024-01-04T16:00:00+01:00'
  end: '2024-01-04T17:00:00+01:00'
  value: 10.573
- start: '2024-01-04T17:00:00+01:00'
  end: '2024-01-04T18:00:00+01:00'
  value: 13.323
- start: '2024-01-04T18:00:00+01:00'
  end: '2024-01-04T19:00:00+01:00'
  value: 14.465
- start: '2024-01-04T19:00:00+01:00'
  end: '2024-01-04T20:00:00+01:00'
  value: 12.5
- start: '2024-01-04T20:00:00+01:00'
  end: '2024-01-04T21:00:00+01:00'
  value: 10.359
- start: '2024-01-04T21:00:00+01:00'
  end: '2024-01-04T22:00:00+01:00'
  value: 10.001
- start: '2024-01-04T22:00:00+01:00'
  end: '2024-01-04T23:00:00+01:00'
  value: 9.486
- start: '2024-01-04T23:00:00+01:00'
  end: '2024-01-05T00:00:00+01:00'
  value: 8.883

raw_tomorrow: 
current_price: 8.502
additional_costs_current_hour: 0
price_in_cents: true
unit_of_measurement: c/kWh
device_class: monetary
icon: mdi:flash
friendly_name: nordpool_kwh_de-lu_eur_3_10_0
```

```
starts_at: 2024-01-04 07:00
cost_at: 0.085
now_cost_rate: 1
icon: mdi:currency-eur
friendly_name: Nordpool Planner Cheapest Hours
```

```
binary_sensor:
  - platform: nordpool_planner
    nordpool_entity: sensor.nordpool_kwh_de_lu_eur_3_10_0
    entity_id: cheapest_hours
    duration: 2
    moving:
      search_length: 24
```

![image](https://github.com/dala318/nordpool_planner/assets/149078331/412466eb-a938-4bf0-9c81-7cecfb342bb0)

![image](https://github.com/dala318/nordpool_planner/assets/149078331/87022409-94b3-4822-9630-ba3d12461483)
