### ISSUE TITLE
Not working, or me Noobing?

### ISSUE THREAD

**Issue by Tom-ahawk** [dala318/nordpool_planner#28]
Looks I cant get this nice integration to work, if I have set it up correctly(?)
Status is ON when it should not be at 15:30.
Do I understand correctly that from my code, I should get ON from 13:00 to 15:00 (two hours) in the 24 hours interval (00-24) on this day?

```
  - platform: nordpool_planner
    nordpool_entity: sensor.nordpool_kwh_oslo
    entity_id: nordpool_planner
    duration:  3              #1 to 5 and specifies how large window of censecutive hours
    var_duration_entity: input_number.nordpool_planner_cheapest_hrs
    moving:
      search_length: 24         # planner searches in a constant window in the future
      var_search_length_entity: input_number.nordpool_planner_search_window
```
![image](https://github.com/user-attachments/assets/f347cb8c-13c0-4413-9024-ecd76e4456be)
